DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `ExecuteQuery`(q TEXT)
BEGIN
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		SELECT q;
			RESIGNAL;
    END;

	SET @s = q;
	PREPARE prep FROM @s;
	EXECUTE prep;
	DEALLOCATE PREPARE prep;
END$$
DELIMITER ;